### ISSUE TITLE
Failure since Version 2.0.4

### ISSUE THREAD

**Issue by hazendaz** [trajano/wagon-git#16]
Attempting to update to 2.0.4 causes failure in site:deploy.  I have to stay on 2.0.3 for this to work.  I've seen this across multiple projects now.  I'm running windows 10 if that helps.  It appears that it is trying to get a native dll in jgit which causes the issue.

java.lang.UnsatisfiedLinkError: Unable to load library 'c': Native library (win32-x86/c.dll) not found in resource path...
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary.<clinit>(JNAUSocketFactory.java:47)
        at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:114)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:93)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:54)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:44)
        at net.trajano.wagon.git.internal.AgentJschConfigSessionFactory.createDefaultJSch(AgentJschConfigSessionFa
java:42)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:247)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:219)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:175)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at net.trajano.wagon.git.internal.AbstractGitWagon.getGit(AbstractGitWagon.java:274)
        at net.trajano.wagon.git.GitWagon.getFileForResource(GitWagon.java:72)
        at net.trajano.wagon.git.internal.AbstractGitWagon.putDirectory(AbstractGitWagon.java:341)
        at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.push(AbstractDeployMojo.java:441)
        at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:323)
        at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:284)
        at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.execute(AbstractDeployMojo.java:166)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more

**Comment by trajano** [comment]
I don't have any issues with Windows 10 short of unable to delete the temp folders on occasion and Ubuntu.

**Comment by trajano** [comment]
It's trying to connect to an agent.  Are you using something with SSH agents?

**Comment by trajano** [comment]
Can you post the full stack trace?  I am missing the key line namely what Exception is it throwing.  If I can add that to the catch clause that may fix the issue.

**Comment by hazendaz** [comment]
I updated the first stack trace which I ran in power shell so you cna see the native library issue.

I ran the same thing in eclipse and got the following instead.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy (default-cli) on project base-parent: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for C:\Users\Jeremy\.ssh\id_rsa -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy (default-cli) on project base-parent: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for C:\Users\Jeremy\.ssh\id_rsa
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for C:\Users\Jeremy\.ssh\id_rsa
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.eclipse.jgit.errors.UnsupportedCredentialItem: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for C:\Users\Jeremy\.ssh\id_rsa
	at org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider.get(UsernamePasswordCredentialsProvider.java:118)
	at org.eclipse.jgit.transport.CredentialsProviderUserInfo.promptPassphrase(CredentialsProviderUserInfo.java:98)
	at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:119)
	at com.jcraft.jsch.Session.connect(Session.java:463)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at net.trajano.wagon.git.internal.AbstractGitWagon.getGit(AbstractGitWagon.java:274)
	at net.trajano.wagon.git.GitWagon.getFileForResource(GitWagon.java:72)
	at net.trajano.wagon.git.internal.AbstractGitWagon.putDirectory(AbstractGitWagon.java:341)
	at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.push(AbstractDeployMojo.java:441)
	at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:323)
	at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:284)
	at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.execute(AbstractDeployMojo.java:166)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by trajano** [comment]
I think something may be wrong with your site deployment environment.  Maybe there's something in the PATH that is causing the issue.  However, what I did was catch `UnsatisfiedLinkError` and make it revert to the default SCH

**Comment by trajano** [comment]
I put it up on 2.0.5-SNAPSHOT

**Comment by hazendaz** [comment]
Thanks.


Sent by Outlook for Android





On Mon, Sep 21, 2015 at 9:41 AM -0700, "Archimedes Trajano" <notifications@github.com> wrote:
I think something may be wrong with your site deployment environment.  Maybe there's something in the PATH that is causing the issue.  However, what I did was catch `UnsatisfiedLinkError` and make it revert to the default SCH


---

**Comment by hazendaz** [comment]
I'll try it tonight.  Thanks for being so quick.  I'll also look more at my setup.


Sent by Outlook for Android





On Mon, Sep 21, 2015 at 9:41 AM -0700, "Archimedes Trajano" <notifications@github.com> wrote:
I put it up on 2.0.5-SNAPSHOT

---

**Comment by trajano** [comment]
So did it work?

**Comment by hazendaz** [comment]
Sorry got help up on work stuff last two nights.  I'll make sure to try this again tonight.


Sent by Outlook for Android





On Tue, Sep 22, 2015 at 6:33 PM -0700, "Archimedes Trajano" <notifications@github.com> wrote:
So did it work?

---

**Comment by hazendaz** [comment]
OK - that looks like it just trimmed down the noise which made me look closer at this stack trace and obviously helped me better see the issue.  I think it's a passphrase issue.  I'll review this further tomorrow as it's likely an issue on my end as you pointed out.

**Comment by trajano** [comment]
OK hope you resolve the issue, I'll release it maybe in a week or so.  Waiting for Mars.1 to come out and make sure everything still works with it.
